baseurl = "http://windyboy.github.io/gh_blog/"
languageCode = ""
title = "My New Hugo Site"
canonifyurls = true
theme = "ghostwriter"

[taxonomies]
  category = "categories"
  tag = "tags"


[Params]
    intro = true
    headline = "My blog headline"
    description = "My hugo blog"
    github = "https://github.com/windyboy"
    gplus = "https://google.com/+windyboy"
    twitter = "https://twitter.com/windysylph"
  	author = "Nikola Tesla"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Projects"
    url = "/project/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 4
